module.exports = {
  darkMode: ["class"],
  content: ["./index.html", "./src/**/*.{ts,tsx,js,jsx}"],
  theme: {
    extend: {
      fontFamily: {
        sans:    ['Inter', 'system-ui', 'sans-serif'],
        body:    ['Inter', 'system-ui', 'sans-serif'],
        display: ['IBM Plex Sans', 'Inter', 'sans-serif'],
        heading: ['IBM Plex Sans', 'Inter', 'sans-serif'],
        mono:    ['ui-monospace', 'SFMono-Regular', 'monospace'],
      },
      colors: {
        navy:    { DEFAULT:'#0F172A', 2:'#1E3A5F', 3:'#2563EB' },
        accent:  { DEFAULT:'#2563EB', hover:'#1D4ED8', light:'#EFF6FF' },
        surface: '#F8FAFC',
        background: '#F8FAFC',
        foreground: '#0F172A',
        border:  { DEFAULT:'#E2E8F0', strong:'#CBD5E1' },
        card: { DEFAULT:'#FFFFFF', foreground:'#0F172A' },
        input: '#E2E8F0',
        ring:  '#2563EB',
        primary:   { DEFAULT:'#2563EB', foreground:'#FFFFFF' },
        secondary: { DEFAULT:'#F8FAFC', foreground:'#0F172A' },
        muted:     { DEFAULT:'#F8FAFC', foreground:'#94A3B8' },
        popover:   { DEFAULT:'#FFFFFF', foreground:'#0F172A' },
        destructive: { DEFAULT:'#B91C1C', foreground:'#FFFFFF' },
        success: { DEFAULT:'#15803D', foreground:'#FFFFFF', bg:'#F0FDF4' },
        warning: { DEFAULT:'#CA8A04', foreground:'#FFFFFF', bg:'#FEFCE8' },
        sidebar: {
          DEFAULT:              '#0F172A',
          foreground:           '#94A3B8',
          primary:              '#2563EB',
          'primary-foreground': '#FFFFFF',
          accent:               'rgba(255,255,255,0.05)',
          'accent-foreground':  '#F1F5F9',
          border:               'rgba(255,255,255,0.06)',
          ring:                 '#2563EB',
        },
        ink: {
          DEFAULT: '#0F172A',
          2: '#1E293B',
          3: '#334155',
          4: '#64748B',
          5: '#94A3B8',
          6: '#E2E8F0',
          7: '#F8FAFC',
        },
      },
      boxShadow: {
        'xs':         '0 1px 2px rgba(0,0,0,.06)',
        'sm':         '0 1px 3px rgba(0,0,0,.1), 0 1px 2px rgba(0,0,0,.06)',
        'md':         '0 4px 6px rgba(0,0,0,.08), 0 2px 4px rgba(0,0,0,.05)',
        'lg':         '0 10px 20px rgba(0,0,0,.1), 0 4px 8px rgba(0,0,0,.05)',
        'xl':         '0 20px 40px rgba(0,0,0,.12), 0 8px 16px rgba(0,0,0,.06)',
        'card':       '0 1px 2px rgba(0,0,0,.06)',
        'card-hover': '0 4px 12px rgba(0,0,0,.1)',
        'sidebar':    '4px 0 24px rgba(0,0,0,.2)',
      },
      keyframes: {
        'accordion-down': { from:{height:'0'}, to:{height:'var(--radix-accordion-content-height)'} },
        'accordion-up':   { from:{height:'var(--radix-accordion-content-height)'}, to:{height:'0'} },
        'fade-up':   { from:{opacity:'0',transform:'translateY(14px)'}, to:{opacity:'1',transform:'translateY(0)'} },
        'scale-in':  { from:{opacity:'0',transform:'scale(.96)'},        to:{opacity:'1',transform:'scale(1)'} },
        'shimmer':   { '0%':{backgroundPosition:'-200% 0'},'100%':{backgroundPosition:'200% 0'} },
        'pulse-soft':{ '0%,100%':{opacity:'1'},'50%':{opacity:'.4'} },
        'spin-fast': { to:{transform:'rotate(360deg)'} },
      },
      animation: {
        'accordion-down': 'accordion-down 0.2s ease-out',
        'accordion-up':   'accordion-up 0.2s ease-out',
        'fade-up':        'fade-up 0.35s ease both',
        'scale-in':       'scale-in 0.25s ease both',
        'shimmer':        'shimmer 1.4s linear infinite',
        'pulse-soft':     'pulse-soft 2s ease-in-out infinite',
      },
      borderRadius: {
        sm:    '6px',
        md:    '10px',
        lg:    '14px',
        xl:    '18px',
        '2xl': '22px',
      },
    }
  },
  plugins: [require("tailwindcss-animate")],
}
