module.exports = {
  darkMode: ["class"],
  content: ["./index.html", "./src/**/*.{ts,tsx,js,jsx}"],
  theme: {
    extend: {
      fontFamily: {
        sans:    ['"Plus Jakarta Sans"', 'system-ui', 'sans-serif'],
        body:    ['"Plus Jakarta Sans"', 'system-ui', 'sans-serif'],
        display: ['"Playfair Display"', 'Georgia', 'serif'],
        heading: ['"Playfair Display"', 'Georgia', 'serif'],
        serif:   ['"Playfair Display"', 'Georgia', 'serif'],
        mono:    ['ui-monospace', 'SFMono-Regular', 'monospace'],
      },
      colors: {
        forest:   { DEFAULT: '#000000' },
        imperial: { DEFAULT: '#1A1A1A' },
        gold:     { DEFAULT: '#000000', light: '#F5F5F5' },
        ochre:    { DEFAULT: '#000000' },
        canvas:   '#FFFFFF',
        background: '#FFFFFF',
        foreground: '#000000',
        border:   { DEFAULT: '#E0E0E0', strong: '#CCCCCC' },
        card:     { DEFAULT: '#FFFFFF', foreground: '#000000' },
        input:    '#E0E0E0',
        ring:     '#000000',
        primary:   { DEFAULT: '#000000', foreground: '#FFFFFF' },
        secondary: { DEFAULT: '#FFFFFF', foreground: '#000000' },
        muted:     { DEFAULT: '#F5F5F5', foreground: '#4D4D4D' },
        popover:   { DEFAULT: '#FFFFFF', foreground: '#000000' },
        destructive: { DEFAULT: '#000000', foreground: '#FFFFFF' },
        success: { DEFAULT: '#000000', foreground: '#FFFFFF', bg: '#F0F0F0' },
        warning: { DEFAULT: '#000000', foreground: '#FFFFFF', bg: '#F5F5F5' },
        urgent:  { DEFAULT: '#000000', bg: '#F5F5F5' },
        resource:{ DEFAULT: '#000000', bg: '#FAFAFA' },
        sidebar: {
          DEFAULT:              '#000000',
          foreground:           '#999999',
          primary:              '#FFFFFF',
          'primary-foreground': '#000000',
          accent:               'rgba(255,255,255,0.06)',
          'accent-foreground':  '#FFFFFF',
          border:               'rgba(255,255,255,0.08)',
          ring:                 '#FFFFFF',
        },
        ink: {
          DEFAULT: '#000000',
          2: '#1A1A1A',
          3: '#333333',
          4: '#4D4D4D',
          5: '#808080',
          6: '#E0E0E0',
          7: '#FFFFFF',
        },
      },
      boxShadow: {
        'xs':   '0 1px 2px rgba(27,36,33,.04)',
        'sm':   '0 1px 3px rgba(27,36,33,.06)',
        'md':   '0 2px 6px rgba(27,36,33,.06)',
        'lg':   '0 4px 12px rgba(27,36,33,.07)',
        'xl':   '0 8px 24px rgba(27,36,33,.08)',
        'card': '0 1px 2px rgba(27,36,33,.04)',
      },
      keyframes: {
        'accordion-down': { from:{height:'0'}, to:{height:'var(--radix-accordion-content-height)'} },
        'accordion-up':   { from:{height:'var(--radix-accordion-content-height)'}, to:{height:'0'} },
        'fade-up':   { from:{opacity:'0',transform:'translateY(10px)'}, to:{opacity:'1',transform:'translateY(0)'} },
        'scale-in':  { from:{opacity:'0',transform:'scale(.97)'},        to:{opacity:'1',transform:'scale(1)'} },
        'shimmer':   { '0%':{backgroundPosition:'-200% 0'},'100%':{backgroundPosition:'200% 0'} },
      },
      animation: {
        'accordion-down': 'accordion-down 0.2s ease-out',
        'accordion-up':   'accordion-up 0.2s ease-out',
        'fade-up':        'fade-up 0.3s ease both',
        'scale-in':       'scale-in 0.2s ease both',
        'shimmer':        'shimmer 1.4s linear infinite',
      },
      borderRadius: {
        sm:    '4px',
        md:    '6px',
        lg:    '8px',
        xl:    '10px',
        '2xl': '12px',
      },
    }
  },
  plugins: [require("tailwindcss-animate")],
}
